/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import static Forms.SelectBeneficiaries.project;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ooad_project.controller;

/**
 *
 * @author Acer
 */
public class AllocateTeam extends javax.swing.JFrame {

    /**
     * Creates new form AllocateTeam
     */
    controller c;
    ArrayList <String> temp;
    static String project;
    public AllocateTeam(String p) {
        initComponents();
        selectvolunteer.setEnabled(false);
        project = p;
        c = new controller();
        temp = c.getremainingvolunteers(p);
        javax.swing.JList<String> temp2 = new javax.swing.JList(temp.toArray());
        volunteerslist=temp2;
        volunteerslist.addListSelectionListener((javax.swing.event.ListSelectionEvent evt) -> {
            volunteerslistValueChanged(evt);
        });
        jScrollPane1.setViewportView(volunteerslist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemname = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        volunteerslist = new javax.swing.JList<>();
        selectvolunteer = new javax.swing.JButton();
        replacemanager = new javax.swing.JButton();
        replacevolunteer = new javax.swing.JButton();
        removevolunteer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        systemname.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        systemname.setForeground(new java.awt.Color(0, 153, 153));
        systemname.setText("Donations Management System");

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 0));
        jButton4.setText("Home");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Volunteers List");

        volunteerslist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        volunteerslist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                volunteerslistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(volunteerslist);

        selectvolunteer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectvolunteer.setForeground(new java.awt.Color(0, 102, 102));
        selectvolunteer.setText("Select Volunteer");
        selectvolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectvolunteerActionPerformed(evt);
            }
        });

        replacemanager.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        replacemanager.setForeground(new java.awt.Color(0, 102, 102));
        replacemanager.setText("Replace Manager");
        replacemanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replacemanagerActionPerformed(evt);
            }
        });

        replacevolunteer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        replacevolunteer.setForeground(new java.awt.Color(0, 102, 102));
        replacevolunteer.setText("Replace Volunteer");
        replacevolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replacevolunteerActionPerformed(evt);
            }
        });

        removevolunteer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        removevolunteer.setForeground(new java.awt.Color(0, 102, 102));
        removevolunteer.setText("Remove Volunteer");
        removevolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removevolunteerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(systemname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectvolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(replacevolunteer)
                            .addComponent(removevolunteer)
                            .addComponent(replacemanager, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemname)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(replacemanager)
                        .addGap(18, 18, 18)
                        .addComponent(replacevolunteer)
                        .addGap(18, 18, 18)
                        .addComponent(removevolunteer)
                        .addGap(18, 18, 18)
                        .addComponent(selectvolunteer)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void volunteerslistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_volunteerslistValueChanged
        // TODO add your handling code here:
        replacemanager.setEnabled(true);
        replacevolunteer.setEnabled(true);
        removevolunteer.setEnabled(true);
        selectvolunteer.setEnabled(true);
    }//GEN-LAST:event_volunteerslistValueChanged

    private void selectvolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectvolunteerActionPerformed
        // TODO add your handling code here:
        String volunteer = volunteerslist.getSelectedValue();
        if(volunteer == null || volunteer.isEmpty())
        {
             JOptionPane.showMessageDialog(this,"No Volunteer Selected","Plain",JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
        int x = c.selectteam(project, volunteer);
        if(x == 0)
        {
            JOptionPane.showMessageDialog(this,"Volunteer Added","Plain",JOptionPane.PLAIN_MESSAGE);
            temp.remove(volunteer);
            javax.swing.JList<String> temp2 = new javax.swing.JList(temp.toArray());
            volunteerslist=temp2;
            jScrollPane1.setViewportView(volunteerslist); 
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Volunteer not selected","Plain",JOptionPane.PLAIN_MESSAGE);
        }
        }        
    }//GEN-LAST:event_selectvolunteerActionPerformed

    private void replacemanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replacemanagerActionPerformed
        // TODO add your handling code here:S        
        ReplaceManager rm = new ReplaceManager(project);
        rm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_replacemanagerActionPerformed

    private void replacevolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replacevolunteerActionPerformed
        // TODO add your handling code here:
        ReplaceVolunteer rv = new ReplaceVolunteer(project);
        rv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_replacevolunteerActionPerformed

    private void removevolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removevolunteerActionPerformed
        // TODO add your handling code here:
        RemoveVolunteer rv = new RemoveVolunteer(project);
        rv.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_removevolunteerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllocateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllocateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllocateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllocateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllocateTeam(project).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removevolunteer;
    private javax.swing.JButton replacemanager;
    private javax.swing.JButton replacevolunteer;
    private javax.swing.JButton selectvolunteer;
    private javax.swing.JLabel systemname;
    private javax.swing.JList<String> volunteerslist;
    // End of variables declaration//GEN-END:variables
}
