/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import ooad_project.controller;

/**
 *
 * @author Acer
 */
public class ReplaceVolunteer extends javax.swing.JFrame {

    /**
     * Creates new form ReplaceVolunteer
     */
    static String project;
    controller c;
    public ReplaceVolunteer(String p) {
        project = p;
        initComponents();
        c = new controller();
        ArrayList <String> temp = c.getcurrentvolunteers(p);
        int s = temp.size();
        String [] projectnames = new String [s];
        for(int i = 0 ; i< s ; i++)
        {
            projectnames[i]=temp.get(i);
        }
        currentvolunteerlist.setModel(new javax.swing.DefaultComboBoxModel<>(projectnames));
        temp = c.getremainingvolunteers(p);
        s = temp.size();
        String [] projectnames2 = new String [s];
        for(int i = 0 ; i< s ; i++)
        {
            projectnames2[i]=temp.get(i);
        }
        newvolunteerlist.setModel(new javax.swing.DefaultComboBoxModel<>(projectnames2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemname = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        currentvolunteer = new javax.swing.JLabel();
        currentvolunteerlist = new javax.swing.JComboBox<>();
        currentvolunteer1 = new javax.swing.JLabel();
        newvolunteerlist = new javax.swing.JComboBox<>();
        replacemanagerbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        systemname.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        systemname.setForeground(new java.awt.Color(0, 153, 153));
        systemname.setText("Donations Management System");

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 0));
        jButton4.setText("Home");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        currentvolunteer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        currentvolunteer.setForeground(new java.awt.Color(0, 102, 102));
        currentvolunteer.setText("Current Volunteer");

        currentvolunteerlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currentvolunteerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentvolunteerlistActionPerformed(evt);
            }
        });

        currentvolunteer1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        currentvolunteer1.setForeground(new java.awt.Color(0, 102, 102));
        currentvolunteer1.setText("New Volunteer");

        newvolunteerlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        newvolunteerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newvolunteerlistActionPerformed(evt);
            }
        });

        replacemanagerbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        replacemanagerbutton.setForeground(new java.awt.Color(0, 102, 102));
        replacemanagerbutton.setText("Replace");
        replacemanagerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replacemanagerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(systemname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(currentvolunteer1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentvolunteer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentvolunteerlist, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newvolunteerlist, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(replacemanagerbutton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(systemname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentvolunteer)
                    .addComponent(currentvolunteerlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentvolunteer1)
                    .addComponent(newvolunteerlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(replacemanagerbutton)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void currentvolunteerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentvolunteerlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentvolunteerlistActionPerformed

    private void newvolunteerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newvolunteerlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newvolunteerlistActionPerformed

    private void replacemanagerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replacemanagerbuttonActionPerformed
        // TODO add your handling code here:
        String name = (String) currentvolunteerlist.getSelectedItem();
        String name2 = (String) newvolunteerlist.getSelectedItem();
        if(c.replacevolunteer(name,name2, project) == 0)
        {
            JOptionPane.showMessageDialog(this,"Volunteer Replaced","Plain",JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Volunteer not replaced","Plain",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_replacemanagerbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplaceVolunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplaceVolunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplaceVolunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplaceVolunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReplaceVolunteer(project).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentvolunteer;
    private javax.swing.JLabel currentvolunteer1;
    private javax.swing.JComboBox<String> currentvolunteerlist;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> newvolunteerlist;
    private javax.swing.JButton replacemanagerbutton;
    private javax.swing.JLabel systemname;
    // End of variables declaration//GEN-END:variables
}
